### ISSUE TITLE
General Chat

### ISSUE THREAD

**Issue by MCloverz** [the-afternetwork-projects/Smile.js#1]
_No description provided._

**Comment by MCloverz** [comment]
Hi!

**Comment by AfterNetwork** [comment]
Oh god. Can you help us create this framework...

**Comment by smileycreations15** [comment]
> Oh god. Can you help us create this framework...

I did some basic UI code cc @AfterNetwork

**Comment by MCloverz** [comment]
> Oh god. Can you help us create this framework...

I know like, nothing about JS... I know how to do some simple if statements and an alert, but that's about it.

**Comment by smileycreations15** [comment]
> > Oh god. Can you help us create this framework...
> 
> I know like, nothing about JS... I know how to do some simple if statements and an alert, but that's about it.

wut?

**Comment by AfterNetwork** [comment]
> > Oh god. Can you help us create this framework...
> 
> I know like, nothing about JS... I know how to do some simple if statements and an alert, but that's about it.

Check out this:
https://www.codecademy.com/learn/introduction-to-javascript

**Comment by MCloverz** [comment]
> > > Oh god. Can you help us create this framework...
> > 
> > 
> > I know like, nothing about JS... I know how to do some simple if statements and an alert, but that's about it.
> 
> Check out this:
> https://www.codecademy.com/learn/introduction-to-javascript

Will do.
I'm currently working on the new ShopBux website, what do you think so far? https://github.com/MCloverz/SSB/edit/master/index.md

**Comment by AfterNetwork** [comment]
> > > > Oh god. Can you help us create this framework...
> > > 
> > > 
> > > I know like, nothing about JS... I know how to do some simple if statements and an alert, but that's about it.
> > 
> > 
> > Check out this:
> > https://www.codecademy.com/learn/introduction-to-javascript
> 
> Will do.
> I'm currently working on the new ShopBux website, what do you think so far? https://github.com/MCloverz/SSB/edit/master/index.md

invite me

**Comment by smileycreations15** [comment]
> > > > Oh god. Can you help us create this framework...
> > > 
> > > 
> > > I know like, nothing about JS... I know how to do some simple if statements and an alert, but that's about it.
> > 
> > 
> > Check out this:
> > https://www.codecademy.com/learn/introduction-to-javascript
> 
> Will do.
> I'm currently working on the new ShopBux website, what do you think so far? https://github.com/MCloverz/SSB/edit/master/index.md

me too cc @MCloverz

**Comment by smileycreations15** [comment]
I WANT TO SCREAM YOU ARE FLOODING MY INBOX WITH GITHUB NOTIFICATIONS

**Comment by MCloverz** [comment]
oof sorry, I will invite you all once the website is done.

**Comment by smileycreations15** [comment]
> oof sorry, I will invite you all once the website is done.

Can you also improve ScratchBux

**Comment by MCloverz** [comment]
> > oof sorry, I will invite you all once the website is done.
> 
> Can you also improve ScratchBux cc @MCloverz

What should I add? I don't know what else.

**Comment by smileycreations15** [comment]
> > > oof sorry, I will invite you all once the website is done.
> > 
> > 
> > Can you also improve ScratchBux cc @MCloverz
> 
> What should I add? I don't know what else.

find something...

**Comment by MCloverz** [comment]
> > > > oof sorry, I will invite you all once the website is done.
> > > 
> > > 
> > > Can you also improve ScratchBux cc @MCloverz
> > 
> > 
> > What should I add? I don't know what else.
> 
> find something...

Okay...

**Comment by smileycreations15** [comment]
@MCloverz @AfterNetwork @the-afternetwork-projects/programming-team I will go to sleep bye I will wake up in 8-10 hours

**Comment by MCloverz** [comment]
> @MCloverz @AfterNetwork @the-afternetwork-projects/programming-team I will go to sleep bye I will wake up in 8-10 hours

Okay.

**Comment by AfterNetwork** [comment]
oof what should we do cc @MCloverz

**Comment by smileycreations15** [comment]
> oof what should we do cc @MCloverz

@MCloverz @AfterNetwork @the-afternetwork-projects/programming-team im back

**Comment by smileycreations15** [comment]
@the-afternetwork-projects/programming-team Should we move it to smileycreations? You will still get credit for the idea.

**Comment by smileycreations15** [comment]
@AfterNetwork Can you accept the collaboration request for the ScratchBux repository and make it better?

**Comment by smileycreations15** [comment]
@MCloverz Please accept the invite to @smileycreations

**Comment by AfterNetwork** [comment]
> @the-afternetwork-projects/programming-team Should we move it to smileycreations? You will still get credit for the idea.

NO

**Comment by AfterNetwork** [comment]
Let's transfer this to the team chat.

**Comment by smileycreations15** [comment]
@AfterNetwork should be merge it? To a new organisation

**Comment by AfterNetwork** [comment]
The AFP Programming team chat is the place to comment and thus should be closed.
